# Generated by Django 4.2.4 on 2023-09-23 09:27

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_project', models.CharField(max_length=200, null=True)),
                ('submitting_RCE', models.CharField(choices=[('hands_on_interactive', 'Hands-on/Interactive'), ('community_asset', 'Community Asset'), ('supported_workplace', 'Supported Workplace Placement'), ('document', 'Documemt'), ('group_meetings', 'Group Meetings')], max_length=200, null=True)),
                ('format_project', models.CharField(max_length=200, null=True)),
                ('delivery', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('hands_on_interactive', 'Hands-on/Interactive'), ('presentation_inperson', 'Presentation (in person)'), ('presentation_virtual', 'Presentation (virtual)'), ('video_resource', 'Video Resource'), ('workshop_hackathon', 'Workshop/Hackathon'), ('group_meeting', 'Convene and administer group meetings'), ('document_toolkit_resource', 'Document/Toolkit/resource'), ('experience', 'Experience'), ('initiative', 'Initiative'), ('community_asset', 'Community Asset')], max_length=200), blank=True, null=True, size=None)),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('biannually', 'Biannually'), ('annually', 'Annually'), ('ongoing', 'Ongoing'), ('once', 'Once'), ('opportunistic_irregularly', 'Opportunistic/Irregularly'), ('permanent_on demand', 'Permanent/On demand')], max_length=200, null=True)),
                ('language_project', models.CharField(max_length=200, null=True)),
                ('web_link', models.URLField(null=True)),
                ('additional_resources', models.TextField(null=True)),
                ('region', models.CharField(choices=[('test', 'Test'), ('demo', 'DEmo')], max_length=200, null=True)),
                ('country', django_countries.fields.CountryField(max_length=2, null=True)),
                ('locations', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('ecosystem', models.CharField(choices=[('agricultural', 'Agricultural'), ('coastal', 'Coastal'), ('dryland', 'Dryland'), ('forest', 'Forest'), ('fresh_water', 'Fresh Water'), ('grassland', 'Grassland'), ('mountain', 'Mountain'), ('urban_peri_urban', 'Urban/Peri-urban'), ('wetlands', 'Wetlands'), ('other', 'Other')], max_length=200, null=True)),
                ('audience', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('general_public', 'General public (any age)'), ('particular_audience', 'Particular target Audience (Please specify)'), ('primary_school_age', 'Primary School age'), ('high_school_age', 'High school age'), ('tertiary_students', 'Tertiary students'), ('teacher_ed', 'Teacher Ed'), ('adults', 'Adults'), ('early_years', 'Early years'), ('adults_60', 'Adults >60')], max_length=200), blank=True, null=True, size=None)),
                ('socio_economic_characteristics', models.TextField(null=True)),
                ('development_challenges', models.TextField(null=True)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('new_report', 'New Report')], max_length=200, null=True)),
                ('start_project', models.DateField(null=True)),
                ('end_project', models.DateField(null=True)),
                ('rationale', models.TextField(null=True)),
                ('objectives', models.TextField(null=True)),
                ('activities_practices', models.TextField(null=True)),
                ('size_academic', models.IntegerField(null=True)),
                ('results', models.TextField(null=True)),
                ('lessons_learned', models.TextField(null=True)),
                ('key_message', models.TextField(null=True)),
                ('relationship_activities', models.TextField(null=True)),
                ('funding', models.TextField(null=True)),
                ('direct_sdgs', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None)),
                ('indirect_sdgs', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None)),
                ('current_partners', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None)),
                ('contact', models.CharField(max_length=200, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('approved', models.BooleanField(default=False, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('linked_users', models.ManyToManyField(blank=True, related_name='linked_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReportImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='unrce.report')),
            ],
        ),
        migrations.CreateModel(
            name='ReportFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='unrce.report')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('website', models.URLField(blank=True, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unrce.report')),
            ],
        ),
        migrations.CreateModel(
            name='Expression_of_interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_of_project', models.CharField(max_length=200)),
                ('contributing_organizations', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('organisation_affiliation', models.CharField(max_length=200)),
                ('email', models.EmailField(default='default@email.com', max_length=254)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
