# Generated by Django 4.2.4 on 2023-08-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_organisation', models.CharField(max_length=200)),
                ('name_project', models.CharField(max_length=200)),
                ('project_description', models.CharField(max_length=200)),
                ('delivery', models.CharField(max_length=200)),
                ('frequency', models.CharField(max_length=200)),
                ('audience', models.CharField(max_length=200)),
                ('current_partners', models.CharField(max_length=200)),
                ('sdg_focus', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=200)),
            ],
        ),
    ]
