# Generated by Django 4.2.4 on 2023-09-23 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unrce', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='contact',
        ),
    ]
