# Generated by Django 4.2.4 on 2023-08-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unrce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expression_of_interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_of_project', models.CharField(max_length=200)),
                ('submitting_rce', models.CharField(max_length=200)),
                ('contributing_organizations', models.CharField(max_length=200)),
                ('format', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('web_link', models.CharField(max_length=200)),
                ('additional_resources', models.CharField(max_length=200)),
                ('policy', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('ecosystem', models.CharField(max_length=200)),
                ('education', models.CharField(max_length=200)),
                ('socio', models.CharField(max_length=200)),
                ('challenges', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('period', models.CharField(max_length=200)),
                ('rationale', models.CharField(max_length=200)),
                ('objectives', models.CharField(max_length=200)),
                ('activites', models.CharField(max_length=200)),
                ('size', models.CharField(max_length=200)),
                ('results', models.CharField(max_length=200)),
                ('lessons', models.CharField(max_length=200)),
                ('key_msg', models.CharField(max_length=200)),
                ('relationships', models.CharField(max_length=200)),
                ('funding', models.CharField(max_length=200)),
                ('pictures', models.CharField(max_length=200)),
                ('sdg', models.CharField(max_length=200)),
                ('priority', models.CharField(max_length=200)),
            ],
        ),
    ]
