# Generated by Django 4.2.6 on 2023-10-13 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unrce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='path/to/upload/directory/'),
        ),
    ]
