# Generated by Django 4.2.4 on 2023-10-14 08:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unrce', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='email_name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='last_name',
        ),
        migrations.AddField(
            model_name='account',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='message',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='profile_sdg',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='account',
            name='sector',
            field=models.CharField(choices=[('mining', 'Mining'), ('retail', 'Retail'), ('finance', 'Finance'), ('construction', 'Construction'), ('trade', 'Trade'), ('transport', 'Transport'), ('agriculture', 'Agriculture'), ('education', 'Education'), ('investment', 'Investment'), ('health_care', 'Health Care'), ('small_business', 'Small Business'), ('postal_and_warehousing', 'Postal and Warehousing'), ('management', 'Management'), ('computers_and_information_technology', 'Computers and Information Technology'), ('law', 'Law'), ('financial_services', 'Financial Services'), ('bank', 'Bank'), ('energy_industry', 'Energy Industry'), ('coal', 'Coal'), ('management_consulting', 'Management Consulting'), ('food_industry', 'Food Industry'), ('agribusiness', 'Agribusiness'), ('infrastructure', 'Infrastructure'), ('engineering', 'Engineering'), ('hospitality_industry', 'Hospitality Industry'), ('commercial_bank', 'Commercial Bank'), ('international_trade', 'International Trade'), ('e_commerce', 'E-Commerce'), ('natural_resource', 'Natural Resource'), ('telecommunications', 'Telecommunications'), ('startup_company', 'Startup Company'), ('electronic_business', 'Electronic Business'), ('hospitality', 'Hospitality'), ('accounting', 'Accounting'), ('entertainment', 'Entertainment'), ('aviation', 'Aviation')], max_length=200, null=True),
        ),
    ]
