# Generated by Django 4.2.4 on 2023-10-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unrce', '0002_remove_account_email_name_remove_account_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='requesting',
            field=models.BooleanField(default=False),
        ),
    ]
