# Generated by Django 4.2.4 on 2023-09-23 10:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unrce', '0002_remove_report_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='direct_sdgs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='report',
            name='indirect_sdgs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
    ]
