# Generated by Django 4.2.4 on 2023-10-01 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unrce', '0002_report_direct_esd_themes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='delivery',
            field=models.CharField(blank=True, choices=[('hands_on_interactive', 'Hands-on/Interactive'), ('presentation_inperson', 'Presentation (in person)'), ('presentation_virtual', 'Presentation (virtual)'), ('video_resource', 'Video Resource'), ('workshop_hackathon', 'Workshop/Hackathon'), ('group_meeting', 'Convene and administer group meetings'), ('document_toolkit_resource', 'Document/Toolkit/resource'), ('experience', 'Experience'), ('initiative', 'Initiative'), ('community_asset', 'Community Asset')], max_length=200, null=True),
        ),
    ]
