# Generated by Django 4.2.4 on 2023-08-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unrce', '0003_report_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
