# Generated by Django 4.2.4 on 2023-10-01 13:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unrce', '0003_alter_report_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='linked_users',
        ),
        migrations.AlterField(
            model_name='report',
            name='delivery',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('hands_on_interactive', 'Hands-on/Interactive'), ('presentation_inperson', 'Presentation (in person)'), ('presentation_virtual', 'Presentation (virtual)'), ('video_resource', 'Video Resource'), ('workshop_hackathon', 'Workshop/Hackathon'), ('group_meeting', 'Convene and administer group meetings'), ('document_toolkit_resource', 'Document/Toolkit/resource'), ('experience', 'Experience'), ('initiative', 'Initiative'), ('community_asset', 'Community Asset')], max_length=200), blank=True, null=True, size=None),
        ),
    ]
