# Generated by Django 4.2.4 on 2023-09-25 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unrce', '0003_alter_report_direct_sdgs_alter_report_indirect_sdgs'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='organizations',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
