# Generated by Django 4.2.4 on 2023-09-25 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unrce', '0004_report_organizations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='organizations',
        ),
    ]
