# Generated by Django 4.2.4 on 2023-08-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unrce', '0004_report_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
