# Generated by Django 4.2.4 on 2023-10-02 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unrce', '0004_remove_report_linked_users_alter_report_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='submitted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
