# Generated by Django 4.2.4 on 2023-10-05 07:24

import datetime
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('unrce', '0005_report_submitted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='address',
        ),
        migrations.RemoveField(
            model_name='report',
            name='country',
        ),
        migrations.RemoveField(
            model_name='report',
            name='format_project',
        ),
        migrations.RemoveField(
            model_name='report',
            name='language_project',
        ),
        migrations.RemoveField(
            model_name='report',
            name='locations',
        ),
        migrations.RemoveField(
            model_name='report',
            name='submitting_RCE',
        ),
        migrations.AlterField(
            model_name='expression_of_interest',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organization',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=200),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(default='Default Organization Name', max_length=200),
        ),
        migrations.AlterField(
            model_name='organization',
            name='website',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='activities_practices',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='report',
            name='additional_resources',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='report',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='audience',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('general_public', 'General public (any age)'), ('particular_audience', 'Particular target Audience (Please specify)'), ('primary_school_age', 'Primary School age'), ('high_school_age', 'High school age'), ('tertiary_students', 'Tertiary students'), ('teacher_ed', 'Teacher Ed'), ('adults', 'Adults'), ('early_years', 'Early years'), ('adults_60', 'Adults >60')], max_length=200), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='report',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=datetime.date(2023, 10, 1)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='delivery',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('hands_on_interactive', 'Hands-on/Interactive'), ('presentation_inperson', 'Presentation (in person)'), ('presentation_virtual', 'Presentation (virtual)'), ('video_resource', 'Video Resource'), ('workshop_hackathon', 'Workshop/Hackathon'), ('group_meeting', 'Convene and administer group meetings'), ('document_toolkit_resource', 'Document/Toolkit/resource'), ('experience', 'Experience'), ('initiative', 'Initiative'), ('community_asset', 'Community Asset')], max_length=200), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='report',
            name='development_challenges',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='report',
            name='direct_esd_themes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='report',
            name='direct_priority_areas',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='report',
            name='direct_sdgs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='report',
            name='ecosystem',
            field=models.CharField(blank=True, choices=[('agricultural', 'Agricultural'), ('coastal', 'Coastal'), ('dryland', 'Dryland'), ('forest', 'Forest'), ('fresh_water', 'Fresh Water'), ('grassland', 'Grassland'), ('mountain', 'Mountain'), ('urban_peri_urban', 'Urban/Peri-urban'), ('wetlands', 'Wetlands'), ('other', 'Other')], default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='report',
            name='end_project',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='frequency',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('biannually', 'Biannually'), ('annually', 'Annually'), ('ongoing', 'Ongoing'), ('once', 'Once'), ('opportunistic_irregularly', 'Opportunistic/Irregularly'), ('permanent_on demand', 'Permanent/On demand')], default='monthly', max_length=200),
        ),
        migrations.AlterField(
            model_name='report',
            name='funding',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='report',
            name='indirect_esd_themes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='report',
            name='indirect_priority_areas',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='report',
            name='indirect_sdgs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='report',
            name='key_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='report',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, default=datetime.date(2023, 10, 1)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='lessons_learned',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='report',
            name='objectives',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='report',
            name='rationale',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='report',
            name='region',
            field=models.CharField(choices=[('perth_metro', 'Perth Metro'), ('great_southern', 'Great Southern'), ('wa', 'WA')], default='perth_metro', max_length=200),
        ),
        migrations.AlterField(
            model_name='report',
            name='relationship_activities',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='report',
            name='results',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='report',
            name='size_academic',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='socio_economic_characteristics',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='report',
            name='start_project',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('new_report', 'New Report')], default='ongoing', max_length=200),
        ),
        migrations.AlterField(
            model_name='report',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='title_project',
            field=models.CharField(default='Default Title', max_length=200),
        ),
        migrations.AlterField(
            model_name='report',
            name='web_link',
            field=models.URLField(blank=True, default=''),
        ),
    ]
