# Generated by Django 4.2.4 on 2023-08-23 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unrce', '0006_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
