# Generated by Django 4.2.4 on 2023-09-25 12:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('unrce', '0006_alter_organization_email_alter_organization_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='current_partners',
        ),
        migrations.AlterField(
            model_name='report',
            name='approved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='linked_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='linked_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
