# Generated by Django 4.2.4 on 2023-09-25 12:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('unrce', '0007_remove_report_current_partners_alter_report_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='linked_users',
            field=models.ManyToManyField(blank=True, related_name='linked_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
