# Generated by Django 4.2.4 on 2023-10-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unrce', '0007_report_sustainable_development_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='report',
            name='frequency',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('biannually', 'Biannually'), ('annually', 'Annually'), ('ongoing', 'Ongoing'), ('once', 'Once'), ('opportunistic_irregularly', 'Opportunistic/Irregularly'), ('permanent_on demand', 'Permanent/On demand')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='region',
            field=models.CharField(choices=[('perth_metro', 'Perth Metro'), ('great_southern', 'Great Southern'), ('wa', 'WA')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(blank=True, choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('new_report', 'New Report')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='title_project',
            field=models.CharField(default='', max_length=200),
        ),
    ]
