# Generated by Django 4.2.4 on 2023-09-07 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unrce', '0012_report_last_modified_report_unique_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='unique_id',
        ),
    ]
