# Generated by Django 4.2.4 on 2023-09-08 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unrce', '0015_excelupload'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='ReportImages',
        ),
    ]
