# Generated by Django 4.2.4 on 2023-09-14 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('unrce', '0017_rename_activites_expression_of_interest_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expression_of_interest',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
