# Generated by Django 4.2.4 on 2023-09-19 09:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unrce', '0019_expression_of_interest_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='project_description',
            new_name='project_description_short',
        ),
        migrations.AddField(
            model_name='report',
            name='project_description_long',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='audience',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('public', 'General Public'), ('students', 'Students'), ('professionals', 'Professionals')], max_length=20), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='report',
            name='current_partners',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='report',
            name='delivery',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('email', 'Email'), ('web', 'Web'), ('print', 'Print')], max_length=20), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='report',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=200),
        ),
    ]
