# Generated by Django 4.2.4 on 2023-09-19 09:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unrce', '0020_rename_project_description_report_project_description_short_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='audience',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('community', 'Community'), ('primary_students', 'Primary School Students'), ('secondary_students', 'Secondary School Students'), ('higher_education', 'Higher Education'), ('teacher_ed', 'Teacher Ed'), ('youth_informal', 'Youth(informal)'), ('youth_formal', 'Youth(formal)'), ('professionals', 'Professionals'), ('public_anyage', 'General Public (any age)'), ('public_older', 'General Public (>60)'), ('public_adults', 'General Public (adults)'), ('public_younger', 'General Public (< 20)'), ('buisness_government', 'Buisness and Government')], max_length=20), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='report',
            name='delivery',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('hands_on_interactive', 'Hands-on/Interactive'), ('community_asset', 'Community Asset'), ('supported_workplace', 'Supported Workplace Placement'), ('document', 'Documemt'), ('group_meetings', 'Group Meetings')], max_length=20), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='report',
            name='frequency',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('annually', 'Annually'), ('biannually', 'Biannually'), ('quarterly', 'Quarterly'), ('seasonally', 'Seasonally'), ('custom', 'Custom')], max_length=200),
        ),
        migrations.AlterField(
            model_name='report',
            name='project_description_long',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
